name: Validate IntelliJ Plugin

on:
  push:
    branches: [ main, master ]
    paths:
      - 'modforge-intellij-plugin/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'modforge-intellij-plugin/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle
      
      - name: Validate Plugin
        working-directory: modforge-intellij-plugin
        run: |
          chmod +x ./gradlew
          ./gradlew validatePluginForProduction
      
      - name: Build Plugin
        working-directory: modforge-intellij-plugin
        run: |
          ./gradlew buildPlugin
      
      - name: Archive Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: modforge-intellij-plugin/build/distributions/*.zip
          retention-days: 5